var lang = {
  LANG0: ['충전','Charge','收费','充電','sạc điện'],
  LANG1: ['구매','buy','采购','購入','mua, tựa vào, bám vào'],
  LANG2: ['어서오세요','Welcome','欢迎','ようこそ','chào mừng'],
  LANG3: ['농장','farm','农场','農場','Nông trại'],
  LANG4: ['메뉴','Menu','菜单','メニュー','Thực đơn'],
  LANG5: ['미지급신고','Report non-payment','报告未付款','未払い申告','Báo cáo việc không thanh toán'],
  LANG6: ['시세','Rate','引用','相場','Trích dẫn'],
  LANG7: ['코인','Coin','硬币','コイン','Đồng tiền'],
  LANG8: ['결제 정보','Billing information','支付信息','お支払い情報','Thông tin thanh toán'],
  LANG9: ['주소','Address','地址','アドレス','Địa chỉ'],
  LANG10: ['복사','Copy','复制','コピー','bản sao'],
  LANG11: ['취소','cancel','取消','キャンセル','hủy bỏ'],
  LANG12: ['구매 예약 신청','Purchase reservation application','购买预订申请','購入予約申し込み','Mua đơn đặt chỗ'],
  LANG13: ['수량','Quantity','数量','数量','Định lượng'],
  LANG14: ['1호','No. 1','第1期','1号','Vấn đề 1'],
  LANG15: ['2호','No. 2','第2期','2号','Vấn đề 2'],
  LANG15A: ['3호','No. 3','第3期','3号','Vấn đề 3'],
  LANG16: ['4호','No. 4','第4期','4号','Vấn đề 4'],
  LANG17: ['5호','No. 5','第5期','5号','Vấn đề 5'],
  LANG18: ['6호','No. 6','第6期','6号','Vấn đề 6'],
  LANG19: ['7호','No. 7','第7期','7号','Vấn đề 7'],
  LANG20: ['크기','Size','尺寸','サイズ','kích thước'],
  LANG21: ['입금 알림','Deposit notification','存款通知','入金通知','Thông báo gửi tiền'],
  LANG22: ['코인이 입금되었습니다','Coins have been deposited','硬币已存入','コインが入金されました','Tiền xu đã được gửi'],
  LANG23: ['성공','success','成功','成功','sự thành công'],
  LANG24: ['닫기','close','关','閉じる','đóng'],
  LANG25: ['요청하신 작업을','The requested operation','请求的操作','要求された作業を','Hoạt động được yêu cầu'],
  LANG26: ['실패하였습니다','Failed','失败的','失敗しました','Thất bại'],
  LANG27: ['농장 구매를 먼저 하셔야 거래가 가능합니다.','You must purchase the farm before you can trade.','您必须先购买农场，然后才能进行交易。','農場の購入を先にする必要があり取引が可能です。','Bạn phải mua trang trại trước khi có thể giao dịch.'],
  LANG28: ['확인','Confirm','确认','確認','Xác nhận'],
  LANG29: ['구매 예약 성공하였습니다','Purchase reservation was successful','购买预订成功','購入予約成功しました','Đặt chỗ mua đã thành công'],
  LANG30: ['잔액이 부족하여 구매 예약에 실패하였습니다','Purchase reservation failed due to insufficient balance','由于余额不足，采购预订失败','残高が不足して購入予約に失敗しました','Đặt trước giao dịch mua không thành công do không đủ số dư'],
  LANG31: ['구매예약 신청시간이 아닙니다','It is not time to apply for purchase reservation','现在没有时间申请购买预订','購入予約申し込み時間がありません','Chưa đến lúc đăng ký đặt trước mua hàng'],
  LANG32: ['시작일','Start date','开始日期','開始日','ngày bắt đầu'],
  LANG33: ['종료일','End Date','结束日期','終了日','Ngày cuối'],
  LANG34: ['합계','Sum','和','合計','Tổng'],
  LANG35: ['개','things','件事','個','điều'],
  LANG36: ['방법 및 순서','Method and order','方法和顺序','方法と手順','Phương pháp và thứ tự'],
  LANG37: ['다음 코스 대로 진행 오리농장에 레벨을 높여가시면 됩니다.','Proceed to the next course You can level up at the duck farm.','继续下一个课程您可以在鸭场升级。','次のコース通りに進めアヒル農場でレベルを上げて行くとします。','Tiến hành khóa học tiếp theo Bạn có thể lên cấp tại trại vịt.'],
  LANG38: ['회원가입','Sign Up','注册','会員登録','Đăng ký'],
  LANG39: ['전체','Total','所有','全体','tất cả'],
  LANG40: ['추천관리','Recommendation management','推荐管理','おすすめの管理','Quản lý đề xuất'],
  LANG41: ['농장관리','Farm management','农场管理','農場管理','Quản lý trang trại'],
  LANG42: ['농장구매일시','Farm Purchase Date','农场购买日期','農場を購入日時','Ngày mua trang trại'],
  LANG43: ['수수료지급일시','Date and time of payment','付款日期和时间','手数料支給日時','Ngày và giờ thanh toán'],
  LANG44: ['추천관리수수료','Recommendation management fee','推荐管理费','おすすめの管理手数料','Phí quản lý đề xuất'],
  LANG45: ['추천관리자','Recommended manager','推荐经理','おすすめ者','Người quản lý được đề xuất'],
  LANG46: ['농장구매금액','Farm purchase amount','农场购买金额','農場購入金額','Số tiền mua trang trại'],
  LANG47: ['관리LEVEL','Management LEVEL','管理级别','管理LEVEL','CẤP QUẢN LÝ'],
  LANG48: ['검색','Search','搜索','検索','Tìm kiếm'],
  LANG49: ['사업진행','Business progress','业务进展','事業進行','Tiến độ kinh doanh'],
  LANG50: ['농장관리수수료','Farm management fee','农场管理费','農場管理手数料','Phí quản lý trang trại'],
  LANG51: ['농장관리레벨','Farm management level','农场管理水平','農場管理レベル','Cấp quản lý trang trại'],
  LANG52: ['레벨농장인원수','Level Farm Number of Persons','等级农场人数','レベル農場人数','Cấp trang trại Số người'],
  LANG53: ['승급일','Upgrade date','升级日期','アップグレード日','Ngày nâng cấp'],
  LANG54: ['황금농장 소개','Golden Farm Introduction','黄金农场介绍','黄金の農場の紹介','Giới thiệu Golden Farm'],
  LANG55: ['베트남 오리 생산량, 전 세계 5위 차지','Vietnam\'s duck production ranks fifth in the world','越南鸭产量居世界第五','ベトナムのアヒルの生産量、世界5位占め','Sản lượng vịt của Việt Nam đứng thứ 5 thế giới'],
  LANG56: ['2014년 기준 베트남의 오리 생산량의 10만 2,646톤 수준으로 전 세계 오리 생산 시장에서 2.4%의 점유율 기록하며 5위를 차지했다.','As of 2014, it ranked 5th with a 2.4% market share in the global duck production market, with a level of 102,646 tons of duck production in Vietnam.','截至2014年，它在全球鸭肉生产市场中以2.4％的市场份额排名第五，越南的鸭肉产量为102,646吨。','2014年基準のベトナムのアヒルの生産量の10万2,646トンのレベルに世界のアヒルの生産市場で2.4％のシェア記録し、5位を占めた。','Tính đến năm 2014, nó đứng thứ 5 với 2,4% thị phần trong thị trường chăn nuôi vịt toàn cầu, với mức sản lượng 102.646 tấn vịt của Việt Nam.'],
  LANG57: ['2012년부터 2014년 동안 2년 1.1%을 보였고 지금까지 세계 2의 오리 생산량으로 오를 만큼 베트남은 오류 생산 특유 국가로 선정되었다.','From 2012 to 2014, it was 1.1% in two years, and so far, Vietnam has been selected as a country peculiar to erroneous production, as it has risen to the world\'s second largest duck production.','2012年から2014年の間に2年1.1％を見せ、これまでの世界2のアヒル生産量に上がるほど、ベトナムは、エラーの生産特有国に選ばれた。','2012年から2014年の間に2年1.1％を見せ、これまでの世界2のアヒル生産量に上がるほど、ベトナムは、エラーの生産特有国に選ばれた。','Từ năm 2012 đến năm 2014, con số này là 1,1% trong hai năm, và cho đến nay, Việt Nam được chọn là quốc gia có sản lượng sai lầm đặc biệt, vì đã vươn lên đứng thứ hai trên thế giới về sản lượng vịt.'],
  LANG58: ['이에 GOLDEN EGG는 3천만 평에 달하는 오리농장을 보유하고 있어 연간 수익도 해가 지날수록 늘어나고 있는 추세이다.','Accordingly, Golden Egg owns a duck farm of 30 million pyeong, and the annual profit is also increasing as the years go by.','因此，金蛋拥有一个拥有3000万坪的鸭场，而且随着时间的流逝，年利润也在增加。','これGOLDEN EGGは3万坪にも及ぶアヒル農場を保有しており、年間売上高もしては過ぎるほど増えている傾向にある。','Theo đó, Golden Egg sở hữu một trang trại vịt 30 triệu pyeong, và lợi nhuận hàng năm cũng tăng dần theo năm tháng.'],
  LANG59: ['비디오 자습서','Video Tutorials','影片教学','ビデオチュートリアル','Video hướng dẫn'],
  LANG60: ['농장관리 농장 및 농장관리자 급여 지급','Farm management Farm and farm manager salary payment','农场管理农场和农场经理工资','ファーム管理ファームとファーム管理者の給与支給','Quản lý trang trại Trả lương cho người quản lý trang trại'],
  LANG61: ['구매 예약 신청','Purchase reservation application','购买预订申请','購入予約申し込み','Mua đơn đặt chỗ'],
  LANG62: ['매칭 완료 판매','Matched sales','相符的销售','マッチング完了販売','Doanh số phù hợp'],
  LANG63: ['해당 회차 이후 판매 대급 입금','Payment of sales amount after the round','回合后支付销售金额','この回目以降の販売デグプ入金','Thanh toán số tiền bán hàng sau vòng đấu'],
  LANG64: ['입금완료일시','Date and time of deposit completion','存款完成的日期和时间','入金完了日時','Ngày và thời gian hoàn thành tiền gửi'],
  LANG65: ['보낸지갑주소','Sent wallet address','发送钱包地址','送信財布アドレス','Địa chỉ ví đã gửi'],
  LANG66: ['수동구매','Manual purchase','手动购买','手動購入','Mua thủ công'],
  LANG67: ['자동구매','Automatic purchase','自动购买','自動購入','Mua hàng tự động'],
  LANG68: ['주문번호','Order Number','订单号','注文番号','Số đơn hàng'],
  LANG69: ['수익금액','Profit amount','利润金额','収入金額','Số tiền lợi nhuận'],
  LANG70: ['구매금액','Purchase amount','采购量','購入金額','Số tiền mua'],
  LANG71: ['판매금액','sale price','销售价格','販売金額','giá bán'],
  LANG72: ['자동구매수수료','Automatic purchase fee','自动购买费用','自動購入手数料','Phí mua tự động'],
  LANG73: ['수수료','fees','费用','手数料','lệ phí'],
  LANG74: ['구매시간','Purchase time','购买时间','購入時間','Thời gian mua hàng'],
  LANG75: ['판매시간','Sales time','销售时间','販売時間','Thời gian bán hàng'],
  LANG76: ['신청일시','Application date and time','申请日期和时间','申し込み日時','Ngày và giờ nộp đơn'],
  LANG77: ['신청','apply','应用','申し込み','ứng dụng'],
  LANG78: ['완료','complete','完成','完了','hoàn thành'],
  LANG79: ['이체금액','Transfer amount','转账金额','変形量','Số tiền chuyển khoản'],
  LANG80: ['출금완료일시','Date and time of withdrawal completion','提款完成的日期和时间','出金完了日時','Ngày và thời gian hoàn thành rút tiền'],
  LANG81: ['수신자주소','Recipient address','收件人地址','受信者のアドレス','Địa chỉ người nhận'],
  LANG82: ['판매','sale','销售','販売','giảm giá'],
  LANG83: ['구매','purchase','采购','購入','mua, tựa vào, bám vào'],
  LANG84: ['지급반영','Reflection of payment','反映付款','支払いを反映','Phản ánh thanh toán'],
  LANG85: ['지급미반영','Not reflected','没有反映','支給未反映','Không phản ánh'],
  LANG86: ['지급','Payments','付款方式','支給','Thanh toán'],
  LANG87: ['미지급','Unpaid','未付','未払い','Chưa thanh toán'],
  LANG88: ['고용지급일시','Employment payment date and time','就业付款日期和时间','雇用支給日時','Ngày và giờ thanh toán việc làm'],
  LANG89: ['관리자명','Administrator name','管理员名称','管理者名','Tên quản trị viên'],
  LANG90: ['관리비용','Management cost','管理费用','管理コスト','Chi phí quản lý'],
  LANG91: ['지급반영일','Payment reflected date','付款反映日期','支給反射で','Ngày phản ánh thanh toán'],
  LANG92: ['농장최대 수익','Farm profit','农场利润','農場最大の利益','Lợi nhuận trang trại'],
  LANG93: ['완성','Complete','完成','完成','hoàn thành'],
  LANG94: ['잔액','balance','平衡','残高','thăng bằng'],
  LANG95: ['평수','Acreage','面积','坪数','Diện tích'],
  LANG96: ['고용농부','Employed Farmer','雇农','雇用農家','Nông dân có việc làm'],
  LANG97: ['농장평수','Farm area','农场面积','ファームエーカー数','Khu trang trại'],
  LANG98: ['고용금액','Employment amount','就业人数','雇用量','Số lượng việc làm'],
  LANG99: ['농부구매','Farm Purchase','农民购买','農家の購入','Mua nông dân'],
  LANG101: ['관리','management','管理','管理','sự quản lý'],
  LANG102: ['성실도','Sincerity','诚意','誠実も','Chân thành'],
  LANG103: ['기술력','technology','技术','技術力','Công nghệ'],
  LANG104: ['고용된 농부가 없습니다','There are no farmers employed','没有雇农','雇用された農家はありません','Không có nông dân nào được tuyển dụng'],
  LANG105: ['마지막 고용일','Last hiring date','上次录用日期','最後の雇用日','Ngày tuyển dụng cuối cùng'],
  LANG106: ['농부 추가','Add farmer','添加农民','農家追加','Thêm nông dân'],
  LANG107: ['농부 급여','Farmer salary','农民工资','農家給与','Lương nông dân'],
  LANG108: ['농부 고용에 성공하였습니다','Succeeded in hiring a farmer','成功聘请农民','農家の雇用に成功しました','Thành công trong việc thuê một nông dân'],
  LANG109: ['USD잔액이 부족합니다','USD balance is insufficient','美元余额不足','USD残高が不足して','Số dư USD không đủ'],
  LANG110: ['회원이 존재하지 않습니다','Member does not exist','成员不存在','会員が存在しません','Thành viên không tồn tại'],
  LANG111: ['존재하지 않는 농부입니다','I am a farmer who does not exist','我是一个不存在的农民','存在しない農家です','Tôi là một nông dân không tồn tại'],
  LANG112: ['시스템에러','system error','系统错误','システムエラー','lỗi hệ thống'],
  LANG113: ['고용하기','Hiring','招聘','雇用する','Thuê mướn'],
  LANG114: ['추가고용하기','Hire additional','雇用更多','追加雇用する','Thuê thêm'],
  LANG115: ['예상산란율','Expected spawning rate','预期产卵率','予想産卵率','Tỷ lệ sinh sản dự kiến'],
  LANG116: ['초대 주소 복사','Copy invitation address','复制邀请地址','招待アドレスをコピー','Sao chép địa chỉ lời mời'],
  LANG117: ['계정 초기화','Reset Account','账户重设','アカウントの初期化','Đặt lại tài khoản'],
  LANG118: ['분실','Forgot','丢失','紛失','mất đi'],
  LANG119: ['아이디','ID','ID','ユーザ名','TÔI'],
  LANG120: ['이메일','Email','电子邮件','メール','e-mail'],
  LANG121: ['귀하의 계정과 연결된 이메일 계정을 입력하면 재설정 지침을 보내드립니다!','Enter your email account associated with your account and we\'ll send you the reset instructions!','输入与您的帐户关联的电子邮件帐户，我们将向您发送重置说明！','あなたのアカウントに関連付けられた電子メールアカウントを入力すると、リセットの指示を送ります！','Nhập tài khoản email được liên kết với tài khoản của bạn và chúng tôi sẽ gửi cho bạn hướng dẫn đặt lại!'],
  LANG122: ['재설정 지침 보내기','Send Reset Instructions','发送重置指令','リセット指示を送る','Gửi hướng dẫn đặt lại'],
  LANG123: ['로그인','Sign In','登录','ログイン','đăng nhập'],
  LANG124: ['회원가입','Sign Up','注册','会員登録','Đăng ký'],
  LANG125: ['아이디,이메일을 입력해주세요','Please enter your ID and email','请输入您的ID和电子邮件','ID、メールアドレスを入力してください','Vui lòng nhập ID và email của bạn'],
  LANG126: ['메일이 전송되었습니다','Your mail has been sent','您的邮件已发送','メールが送信されました','Thư của bạn đã được gửi'],
  LANG127: ['이메일 또는 아이디를 확인해주세요','Please check your email or ID','请检查您的电子邮件或ID','メールまたはIDを確認してください','Vui lòng kiểm tra email hoặc ID của bạn'],
  LANG128: ['농장레벨','Farm level','农场级别','ファームレベル','Cấp trang trại'],
  LANG129: ['농장평수','Farm area','农场面积','ファームエーカー数','Khu trang trại'],
  LANG130: ['보유자산','Holding assets','持有资产','保有資産','Nắm giữ tài sản'],
  LANG131: ['코인 입금','Coin deposit','存入硬币','コイン入金','Gửi tiền xu'],
  LANG132: ['코인 출금','Coin withdrawal','取款','コイン出金','Rút tiền xu'],
  LANG133: ['다음 매칭 시간까지','Benefit deposit','直到下一个匹配时间','次のマッチング時間まで','Cho đến lần khớp kế tiếp'],
  LANG134: ['잠시만 기다려주십시오.','Benefit withdrawal','请稍候。','しばらくお待ちください。','Xin vui lòng chờ trong giây lát.'],
  LANG135: ['입금','deposit','存款','入金','tiền gửi'],
  LANG136: ['출금','withdrawal','退出','出金','rút lui'],
  LANG137: ['농장 관리자 급여','Farm manager salary','农场经理工资','ファーム管理者の給与','Lương quản lý trang trại'],
  LANG138: ['농장관리자에게 급여를 지급하셔야 합니다.','Salaries must be paid to the farm manager.','工资必须支付给农场经理。','農場管理者に給与を支給する必要があります。','Tiền lương phải trả cho người quản lý trang trại.'],
  LANG139: ['매칭 시간','Matching time','比赛时间','マッチング時間','Thời gian phù hợp'],
  LANG140: ['자동설정','Auto Set','自动设定','自動設定','Cài đặt tự động'],
  LANG141: ['자동','Automatic','自动','自動','Tự động'],
  LANG142: ['수동','manual','手册','手動','sổ tay'],
  LANG143: ['오늘의 구매 예약 및 매칭 시간.','Today\'s purchase reservation and matching time.','今天的购买预订和匹配时间。','今日の購入予約とのマッチングの時間。','Đặt trước mua hôm nay và thời gian khớp.'],
  LANG144: ['자동구매 변환시 수동 구매 예약건은 초기화 됩니다.','In case of automatic purchase conversion, manual purchase reservations are reset.','在自动购买转换的情况下，将重置手动购买预订。','自動購入変換時手動購入予約の件は初期化されます。','Trong trường hợp chuyển đổi mua tự động, đặt trước mua thủ công được đặt lại.'],
  LANG145: ['오늘 매칭 카운트','Today Matching Count','今天的匹配数','今日マッチングカウント','Số lượng phù hợp hôm nay'],
  LANG146: ['회차','Round','回合','回送','Tròn'],
  LANG147: ['시작','Start','开始','開始','khởi đầu'],
  LANG148: ['끝','End','结束','最後','Kết thúc'],
  LANG149: ['상태','Status','州','状態','tiểu bang'],
  LANG150: ['진행중','Proceeding','进行中','進行中','Đang tiến hành'],
  LANG151: ['진행완료','Progress completed','进度完成','進行完了','Tiến độ hoàn thành'],
  LANG152: ['남은시간','Time remaining','剩余时间','残り時間','Thời gian còn lại'],
  LANG153: ['자동 거래는 본인 보유 USD 500 이상 보유 하셔야 합니다','Automatic transactions must be held at least USD 500','自动交易必须至少持有500美元','自動取引は本人保有USD500以上保有する必要があります','Các giao dịch tự động phải có ít nhất 500 USD'],
  LANG154: ['완료','complete','完成','完了','hoàn thành'],
  LANG155: ['대기중','Waiting','等候','待機中','Đang chờ đợi'],
  LANG156: ['예약','reservation','保留','予約','Dự phòng'],
  LANG157: ['다국어 지원','We\'re multilingual','多语种支持','多言語サポート','Hỗ trợ đa ngôn ngữ'],
  LANG158: ['언어를 선택하세요','Choose your Language','请选择一种语言','言語を選択してください','Vui lòng chọn một ngôn ngữ'],
  LANG159: ['회원 아이디','User ID','会员ID','会員IDを','Mã thành viên'],
  LANG160: ['골든덕에 오신걸 환영합니다','Welcome to the Golden duck','欢迎来到金鸭','ゴールデンのおかげで歓迎します','Chào mừng bạn đến với Golden Duck'],
  LANG161: ['회원정보','Profile','个人资料','会員情報','Hồ sơ'],
  LANG162: ['나의정보','My information','我的信息','私の情報','Thông tin của tôi'],
  LANG163: ['출금지갑주소','Withdrawal wallet address','提款钱包地址','出金財布アドレス','Địa chỉ ví rút tiền'],
  LANG164: ['보안관리','Security management','安全管理','セキュリティ管理','Quản lý an ninh'],
  LANG165: ['조직도','Organization chart','组织结构图','組織','Sơ đồ tổ chức'],
  LANG166: ['조직표','Organization chart','组织结构图','組織','Sơ đồ tổ chức'],
  LANG167: ['공지사항','Notice','注意','お知らせ','Để ý'],
  LANG168: ['농장관리','Farm management','农场管理','農場管理','Quản lý trang trại'],
  LANG169: ['농장구매내역','Farm purchase history','农场购买历史','農場の購入履歴','Lịch sử mua trang trại'],
  LANG170: ['구매 신청','Purchase application','购买申请','購買申請','Đơn mua hàng'],
  LANG171: ['판매/구매내역','Sales/purchase history','销售/购买历史','販売/購入履歴','Lịch sử bán hàng / mua hàng'],
  LANG172: ['입금내역','Deposit details','存款详情','入金内訳','Chi tiết tiền gửi'],
  LANG173: ['출금내역','Withdrawal history','提款历史','出金内訳','Lịch sử rút tiền'],
  LANG174: ['보너스 내역','Bonus details','奖金详情','ボーナス内訳','Chi tiết tiền thưởng'],
  LANG175: ['서비스 센터','service center','服务中心','サービスセンター','Trung tâm dịch vụ'],
  LANG176: ['설정','settings','设定值','設定','Cài đặt'],
  LANG177: ['언어','Language','语言','言語','ngôn ngữ'],
  LANG178: ['다크 모드','Dark Mode','暗模式','ダークモード','Chế độ tối'],
  LANG179: ['로그아웃 되었습니다','You are logged out','ログアウトしました','您已登出','Bạn đã đăng xuất'],
  LANG180: ['휴대폰 번호','Phone number','手机号码','携帯電話番号','Số điện thoại'],
  LANG181: ['추천인','Recommender','推荐人','オススメ','Người giới thiệu'],
  LANG182: ['비밀번호 변경','Change Password','更改密码','パスワードの変更','Đổi mật khẩu'],
  LANG183: ['비밀번호','Password','密码','パスワード','mật khẩu'],
  LANG184: ['새 비밀번호','New Password','新密码','新しいパスワード','Mật khẩu mới'],
  LANG185: ['비밀번호 확인','Confirm New Password','确认密码','パスワードの確認','Xác nhận mật khẩu'],
  LANG186: ['인증번호','Authentication Code','认证编号','認証番号','Số chứng nhận'],
  LANG187: ['저장','Save','保存','保存','Tiết kiệm'],
  LANG188: ['메일 전송','Email Send','发送邮件','メール転送','Đang gửi thư'],
  LANG189: ['전송 실패','Failed to send','发送失败','送信に失敗し','Gửi thất bại'],
  LANG190: ['이메일 전송하였습니다','I sent an email','我发了一封电子邮件','メール送信しました','tôi đã gửi một thư điện tử'],
  LANG191: ['새로운 비밀번호가 일치하지 않습니다','New password does not match','新密码不匹配','新しいパスワードが一致しません','Mật khẩu mới không khớp'],
  LANG192: ['값을 모두 입력해주세요','Please enter all values','请输入所有值','値をすべて入力してください','Vui lòng nhập tất cả các giá trị'],
  LANG193: ['인증번호를 입력해주세요','Please enter your verification number','请输入您的验证码','認証番号を入力してください','Vui lòng nhập số xác minh của bạn'],
  LANG194: ['정상변경 처리되었습니다','Normal change has been processed','正常更改已处理','通常の変更処理された','Thay đổi bình thường đã được xử lý'],
  LANG195: ['잘못된 접속 경로입니다. 다시 로그인 부탁드립니다.','Bad connection path. Please log in again.','连接路径错误。 请重新登录。','不適切接続パスです。再度ログインお願いします。','Đường dẫn kết nối không hợp lệ. Xin vui lòng đăng nhập lại.'],
  LANG196: ['기존 비밀번가 맞지 않습니다','Existing Secret Avenue doesn\'t fit','现有的秘密大道不适合','既存の秘密アベニュー合わない','Đại lộ bí mật hiện tại không phù hợp'],
  LANG197: ['승인받지 않았습니다','Not approved','不批准','承認されていません','Không được chấp thuận'],
  LANG198: ['변경 실패! 관리자에게 문의하세요','変更に失敗し！管理者に問い合わせてください','更改失败！ 与您的管理员联系','変更に失敗し！管理者に問い合わせてください','Thay đổi không thành công! Kết nối với quản trị viên của bạn'],
  LANG199: ['이미 승인 처리된 인증번호 입니다','This is a verification number that has already been approved','这是已经批准的验证码','すでに承認処理された認証番号です','Đây là số xác minh đã được phê duyệt'],
  LANG200: ['인증번호가 맞지 않습니다','The authentication number is not correct','验证码不正确','認証番号が一致しません','Số xác thực không đúng'],
  LANG201: ['인증번호 발행 3분 초과되었습니다. 인증번호를 다시 받아주십시오','Issuance of the authentication number has exceeded 3 minutes. Please get your verification number again','认证号码的发放已超过3分钟 请再次获取您的验证码','認証番号発行3分を超えました。認証番号を再受けてください','Việc cấp số xác thực đã quá 3 phút. Vui lòng lấy lại số xác minh của bạn'],
  LANG202: ['공유','Share','分享','共有','chia sẻ'],
  LANG203: ['홈화면 추가','Add to Home Screen','添加主屏幕','ホーム画面を追加','添加 主 屏幕'],
  LANG204: ['지갑 별명','Wallet nickname','钱包昵称','財布ニックネーム','Biệt hiệu ví'],
  LANG205: ['지갑 주소','Wallet address','钱包地址','財布アドレス','Địa chỉ ví'],
  LANG206: ['삭제','delete','删除','削除','xóa bỏ'],
  LANG207: ['삭제 성공','Delete success','删除成功','削除に成功','Xóa thành công'],
  LANG208: ['삭제 실패','Deletion failed','删除失败','削除に失敗し','Xóa không thành công'],
  LANG209: ['정상등록 처리되었습니다','Normal registration has been processed','正常注册已处理','通常の登録処理された','Đăng ký bình thường đã được xử lý'],
  LANG210: ['잘못된 접속 경로입니다. 다시 로그인 부탁드립니다.','Bad connection path. Please log in again.','连接路径错误。 请重新登录。','不適切接続パスです。再度ログインお願いします。','Đường dẫn kết nối không hợp lệ. Xin vui lòng đăng nhập lại.'],
  LANG211: ['출금코인을 선택하여 주십시오','Please select a withdrawal coin','请选择提款硬币','出金コインを選択してください','Vui lòng chọn đồng tiền rút'],
  LANG212: ['본인코인 주소가 없습니다. 관리자에게 문의하여주십시오','I do not have my own coin address. Please contact the administrator','我没有自己的投币地址。 请联系管理员','本人コインアドレスがありません。管理者に連絡してください','Tôi không có địa chỉ tiền xu của riêng mình. Vui lòng liên hệ với quản trị viên'],
  LANG213: ['코인주소는 이미 출금 주소로 등록되어 있습니다','Coin address is already registered as withdrawal address','硬币地址已被注册为提款地址','コインアドレスは既に出金アドレスに登録されています','Địa chỉ tiền xu đã được đăng ký làm địa chỉ rút tiền'],
  LANG214: ['출금 코인 주소를 입력하여 주십시오','Please enter your withdrawal coin address','请输入您的提款硬币地址','出金コインアドレスを入力してください','Vui lòng nhập địa chỉ rút tiền của bạn'],
  LANG215: ['인증이후 신청하여 주십시오','Please apply after certification','认证后请申请','認証後に申請してください','Vui lòng đăng ký sau khi chứng nhận'],
  LANG216: ['변경 실패! 관리자에게 문의하세요','Change failed! Contact your administrator','更改失败！ 与您的管理员联系','変更に失敗し！管理者に問い合わせてください','Thay đổi không thành công! Kết nối với quản trị viên của bạn'],
  LANG217: ['10일 10% 이상 출금이 불가합니다','You cannot withdraw more than 10% for 10 days','您不能在10天内提取超过10％的款项','10日10％以上出金ができません','Bạn không thể rút nhiều hơn 10% trong 10 ngày'],
  LANG218: ['출금신청','Withdrawal application','提款申请','出金の申請','Đơn rút tiền'],
  LANG219: ['출금 신청을 하기 위해서는 출금 지갑 주소를 등록하셔야 합니다.','In order to apply for withdrawal, you must register your withdrawal wallet address.','为了申请提款，您必须注册您的提款钱包地址。','出金申請をするためには、出金財布アドレスを登録する必要があります。','Để đăng ký rút tiền, bạn phải đăng ký địa chỉ ví rút tiền của mình.'],
  LANG220: ['잔액','Your Balance','平衡','残高','thăng bằng'],
  LANG221: ['출금한도','Income','輸入','收入','thu nhập'],
  LANG222: ['신청금액','Expenses','守卫','経費','bảo vệ'],
  LANG223: ['출금금액','Withdrawal amount','提款金额','出金金額','Số tiền rút'],
  LANG224: ['예정','Expected','预期','予定','Hy vọng'],
  LANG225: ['출금신청이 완료되었습니다.','The withdrawal application has been completed.','提款申请已完成。','出金申請が完了しました。','Đơn rút tiền đã được hoàn tất.'],
  LANG226: ['잔액이 부족합니다','Not enough balance','余额不足','残高が不足して','Không đủ số dư'],
  LANG227: ['메일주소 등록후 사용하십시오!','Please use it after registering your e-mail address!','注册您的电子邮件地址后，请使用它！','メールアドレスの登録後に使用してください！','Vui lòng sử dụng sau khi đăng ký địa chỉ e-mail của bạn!'],
  LANG228: ['인증번호 승인 이후 사용하십시오!','Use after approval of the authentication number!','验证码批准后使用！','認証番号の承認後に使用してください！','Sử dụng sau khi phê duyệt số xác thực!'],
  LANG229: ['출금신청 대기중인 코인이 존재합니다.','There are coins waiting for withdrawal request.','有硬币等待提款请求。','出金の申請待ちコインが存在します。','Có xu đang chờ yêu cầu rút tiền.'],
  LANG230: ['3시간 안에 출금 코인금액이 존재합니다','Withdrawal coin amount exists within 3 hours','3小时内有提现硬币数量','3時間以内に出金コインの価値が存在します','Số tiền rút được tồn tại trong vòng 3 giờ'],
  LANG231: ['주간 출금한도를 초과하였습니다.','The weekly withdrawal limit has been exceeded.','已超出每周提款限额。','週間出金限度を超えました。','Đã vượt quá giới hạn rút tiền hàng tuần.'],
  LANG232: ['출금 신청 실패! 관리자에게 문의하세요','Withdrawal application failed! Contact your administrator','提款申请失败！ 与您的管理员联系','出金の申請に失敗！管理者に問い合わせてください','Ứng dụng rút tiền không thành công! Kết nối với quản trị viên của bạn'],
  LANG233: ['인증서가 발행되지 않았습니다','No certificate has been issued','尚未颁发证书','証明書が発行豚ませんでした','Không có chứng chỉ nào được cấp'],
  LANG234: ['비밀번호 찾기','Forgot your password','忘记密码了吗','パスワードを忘れた','Quên mật khẩu'],
  LANG235: ['아이디 비밀번호를 입력해주세요','Please enter your ID and password','请输入您的用户名和密码','ユーザー名パスワードを入力してください','Vui lòng nhập ID và mật khẩu của bạn'],
  LANG236: ['아이디또는 비밀번호가 잘못되었습니다.','ID or password is incorrect.','ID或密码错误。','ユーザー名、またはパスワードが間違っています。','ID hoặc mật khẩu không chính xác.'],
  LANG237: ['국가','country','国家','国','Quốc gia'],
  LANG238: ['중복확인','double check','再检查一遍','重複確認','kiểm tra hai lần'],
  LANG239: ['검색어를 입력해주세요','Please enter a search term','请输入一个搜索词','検索用語を入力してください','Vui lòng nhập một cụm từ tìm kiếm'],
  LANG240: ['비밀번호가 일치하지 않습니다','Passwords do not match','密码不匹配','パスワードが一致しません','Mật khẩu không phù hợp'],
  LANG241: ['아이디 중복검사를 먼저 진행 해 주세요','Please do the duplicate ID check first','请先进行重复的ID检查','ユーザ名の重複検査を先に進めてください','Vui lòng kiểm tra ID trùng lặp trước'],
  LANG242: ['가입을 축하드립니다!','Congratulations on signing up!','恭喜您注册！','登録おめでとうございます！','Chúc mừng bạn đã đăng ký!'],
  LANG243: ['중복된 아이디 입니다','This is a duplicate ID','这是重复的ID','重複したIDです','Đây là một ID trùng lặp'],
  LANG244: ['비밀번호를 입력하세요','Please enter a password','请输入密码','パスワードを入力してください','Vui lòng nhập mật khẩu'],
  LANG245: ['중복 가입된 핸드폰 번호입니다.','This is a duplicate mobile phone number.','这是重复的手机号码。','重複登録された携帯電話の番号です。','Đây là một số điện thoại di động trùng lặp.'],
  LANG246: ['추천인을 확인 인하세요','Check in the referral','签入推荐','オススメを確認引き下げてください','Kiểm tra trong giới thiệu'],
  LANG247: ['이미 승인 받은 인증 번호입니다','This is a verification number that has already been approved.','这是已经批准的验证码。','すでに承認された認証番号です','Đây là số xác minh đã được phê duyệt.'],
  LANG248: ['인증 번호를 확인 하여 주십시오','Please check the authentication number','请检查验证码','認証番号を確認してください','Vui lòng kiểm tra số xác thực'],
  LANG249: ['가입에 실패하였습니다','Failed to join','加入失败','登録に失敗しました','Không tham gia được'],
  LANG250: ['아이디 중복검사름 먼저 진행해주세요','Please proceed with the duplicate ID check first','请先进行重复的ID检查','ユーザ名の重複検査名先に進めてください','Vui lòng tiến hành kiểm tra ID trùng lặp trước tiên'],
  LANG251: ['이메일을 입력해주세요','Please enter your e-mail','请输入您的电子邮件','メールアドレスを入力してください','Vui lòng nhập địa chỉ email của bạn'],
  LANG252: ['아이디를 입력해주세요','Please enter your ID','请输入您的身份证','IDを入力してください','Vui lòng nhập ID của bạn'],
  LANG253: ['사용 가능한 아이디입니다','Username is available','用户名可用','使用可能なIDです','Tên người dùng có sẵn'],
  LANG254: ['이용할수없는 아이디입니다','ID is not available','ID不可用','利用できないIDです','ID không có sẵn'],
  LANG255: ['중복된 이메일','Duplicate email','电子邮件重复','重複した電子メール','Email trùng lặp'],
  LANG256: ['수동 구매 전환이후 구매예약 하여주십시오','Please make a purchase reservation after manual purchase conversion','手动转换购买后，请进行购买预订','手動コンバージョン以降の購入予約してください','Vui lòng đặt trước mua hàng sau khi chuyển đổi mua hàng thủ công'],
  LANG257: ['aaa1','aaa2','aaa3','aaa4','aa5a'],
  LANG258: ['aaa1','aaa2','aaa3','aaa4','aa5a'],
  LANG259: ['aaa1','aaa2','aaa3','aaa4','aa5a'],
  LANG260: ['보낸주소','Received address','发件人地址','送信アドレス','Địa chỉ của người gửi'],
  LANG261: ['데이터가 없습니다.','No data','没有数据','データがありません','Không có dữ liệu'],
  LANG262: ['지갑 생성','Create Wallet','钱包创作','財布生成','Tạo ví'],
  LANG263: ['코인 입금 대기내역','Waiting for Pending List','硬币存款等待历史','コイン入金待ちの履歴','Lịch sử chờ gửi tiền xu'],
  LANG264: ['생성에 성공하였습니다','Creation success','创作成功','生成に成功しました','Tạo thành công'],
  LANG265: ['지갑이 없습니다','NO WALLET','我没有钱包','財布はありません','Tôi không có ví'],
  LANG266: ['출금지갑주소','Withdraw Address','提款钱包地址','出金財布アドレス','Địa chỉ ví rút tiền'],
  LANG267: ['주소','Address','地址','アドレス','Địa chỉ'],
  LANG268: ['지갑을 선택하세요,','Select a Wallet','选择一个钱包','財布を選択してください','Chọn một chiếc ví'],
  LANG269: ['인증번호를 먼저 전송해주세요','Please send the verification number first','请先发送验证码','認証番号を先に送信してください','Vui lòng gửi số xác minh trước'],
  LANG270: ['인증코드를 입력해주세요','Please enter the verification code','请输入验证码','認証コードを入力してください','Vui lòng nhập mã xác nhận'],
  LANG271: ['정상등록 처리되었습니다','Normal registration has been processed','正常注册已处理','通常の登録処理された','Đăng ký bình thường đã được xử lý'],
  LANG272: ['잘못된 접속 경로입니다. 다시 로그인 부탁드립니다.','Bad connection path. Please log in again.','连接路径错误。 请重新登录。','不適切接続パスです。再度ログインお願いします。','Đường dẫn kết nối không hợp lệ. Xin vui lòng đăng nhập lại.'],
  LANG273: ['출금코인을 선택하여 주십시오','Please select a withdrawal coin','请选择提款硬币','出金コインを選択してください','Vui lòng chọn đồng tiền rút'],
  LANG274: ['본인코인 주소가 없습니다','I do not have my own coin address','我没有自己的投币地址','本人コインアドレスがありません','Tôi không có địa chỉ tiền xu của riêng mình'],
  LANG275: ['코인주소는 이미 출금 주소로 등록되어 있습니다','Coin address is already registered as withdrawal address','硬币地址已被注册为提款地址','コインアドレスは既に出金アドレスに登録されています','Địa chỉ tiền xu đã được đăng ký làm địa chỉ rút tiền'],
  LANG276: ['출금 코인 주소를 입력하여 주십시오','Please enter your withdrawal coin address','请输入您的提款硬币地址','出金コインアドレスを入力してください','Vui lòng nhập địa chỉ rút tiền của bạn'],
  LANG277: ['인증이후 신청하여 주십시오','Please apply after certification','认证后请申请','認証後に申請してください','Vui lòng đăng ký sau khi chứng nhận'],
  LANG278: ['이미 승인 처리된 인증번호 입니다','This is a verification number that has already been approved','这是已经批准的验证码','すでに承認処理された認証番号です','Đây là số xác minh đã được phê duyệt'],
  LANG279: ['인증번호가 맞지 않습니다','The authentication number is not correct','验证码不正确','認証番号が一致しません','Số xác thực không đúng'],
  LANG280: ['인증번호 발행 5분 초과되었습니다. 인증번호를 다시 받아주십시오','Issuance of the authentication number has exceeded 3 minutes. Please get your verification number again','认证号码的发放已超过3分钟 请再次获取您的验证码','認証番号発行3分を超えました。認証番号を再受けてください','Việc cấp số xác thực đã quá 3 phút. Vui lòng lấy lại số xác minh của bạn'],
  LANG281: ['ICK 에 오신걸 환영합니다.','Welcome to the ICK Wallet','欢迎来到ICK','ICKへようこそ','Chào mừng đến với ICK'],
  LANG282: ['출금주소 등록','Register withdrawal address','注册提款地址','出金アドレス登録','Đăng ký địa chỉ rút tiền'],
  LANG283: ['거래정보','Transaction information','交易信息','取引情報','Thông tin giao dịch'],
  LANG284: ['코인입금','Coin deposit','硬币存款','コイン入金','Tiền gửi'],
  LANG285: ['코인이체','Coin transfer','投币','コイン変形','Chuyển tiền xu'],
  LANG286: ['거래내역','Transaction history','交易记录','取引の詳細','Lịch sử giao dịch'],
  LANG287: ['고객센터','Service center','服务中心','お客様センター','Trung tâm dịch vụ'],
  LANG288: ['서비스센터','Service Center','服务中心','サービスセンター','Trung tâm dịch vụ'],
  LANG289: ['지갑공유하기','Share your wallet','分享你的钱包','財布共有する','Chia sẻ ví của bạn'],
  LANG290: ['홈화면추가','Add home screen','添加主屏幕','ホーム画面を追加','Thêm màn hình chính'],
  LANG291: ['공지사항이 없습니다','No notice','没有公告','お知らせはありません','Không có thông báo'],
  LANG292: ['계정생성','Create Account','创建帐号','アカウントの作成','Tạo tài khoản'],
  LANG293: ['아래에 이메일 주소를 입력하면 재설정 지침을 보내드립니다.',"Enter your email addresse below and we'll send you the reset instructions.",'在下面输入您的电子邮件地址，我们将向您发送重置说明','下にメールアドレスを入力すると、リセットの指示を送信します','Nhập địa chỉ email của bạn vào bên dưới và chúng tôi sẽ gửi cho bạn hướng dẫn đặt lại'],
  LANG294: ['재설정 지침 보내기','Send Reset Instructions','发送重置指令','リセット指示を送る','Gửi hướng dẫn đặt lại'],
  LANG295: ['계정 재 설정','Reset Account','账户重置','アカウントの再設定','Đặt lại tài khoản'],
  LANG296: ['기억하기','Remember Me','记得','記憶する','Nhớ lại'],
  LANG297: ['휴대폰으로 로그인하기','Sign In with phone','用手机登录','携帯電話でログインする','Đăng nhập bằng điện thoại của bạn'],
  LANG298: ['휴대폰 인증',' Phone Certification','手机认证','携帯電話認証','chứng nhận điện thoại di động'],
  LANG299: ['로그인 하러가기','Sign In Here','去登录','ログインしに行く','Đi đến đăng nhập'],
  LANG300: ['이미 사용중인 번호입니다','This number is already in use','该号码已被使用','既に使用されている番号です','Số này đã được sử dụng'],
  LANG301: ['휴대폰 인증을 먼저 진행해주세요','Please proceed with mobile phone authentication first','请先进行手机验证','携帯電話の認証を先に進めてください','Vui lòng tiến hành xác thực điện thoại di động trước'],
  LANG302: ['수량','Amount','价钱','金額','Giá bán'],
  LANG303: ['주소확인','Address check','地址验证','アドレスを確認する','Xác minh địa chỉ'],
  LANG304: ['이체 주소','Transfer Wallet Address','转账地址','変形アドレス','Chuyển địa chỉ'],
  LANG305: ['진행하기','Continue','继续','進行する','Tiến hành'],
  LANG306: ['사용가능한 주소입니다','This is a usable address','这是一个可用的地址','使用可能なアドレスです','Đây là một địa chỉ có thể sử dụng'],
  LANG307: ['잘못된 주소입니다','Wrong address','错误的地址','間違ったアドレスです','Sai địa chỉ'],
  LANG308: ['출금 주소 검증을 먼저 진행해주세요','Please verify withdrawal address first','请先确认提款地址','出金アドレス検証を先に進めてください','Vui lòng xác minh địa chỉ rút tiền trước'],
  LANG309: ['출금 코인을 선택해주세요','Please select a withdrawal coin','请选择提款硬币','出金コインを選択してください','Vui lòng chọn đồng tiền rút'],
  LANG400: ['출금 금액을 입력하세요','Please enter the withdrawal amount','请输入提款金额','出金金額を入力してください','Vui lòng nhập số tiền rút'],
  LANG401: ['이체 실패 하였습니다 (잔액, 혹은 수수료부족)','Transfer failed (balance or lack of commission)','转移失败（余额或佣金不足）','変形失敗しました（残高、あるいは手数料不足）','Chuyển khoản không thành công (số dư hoặc thiếu hoa hồng)'],
  LANG402: ['전송이 완료되었습니다','Transfer is complete','转移完成','転送が完了しました','Chuyển hoàn tất'],
  LANG403: ['외부 이체가 불가능합니다.관리자에게 문의하십시오','External transfer is not possible, please contact the administrator','无法进行外部转移，请联系管理员','外部変形ができません。管理者に問い合わせてください','Không thể chuyển ra bên ngoài, vui lòng liên hệ với quản trị viên'],
  LANG404: ['aaa1','aaa2','aaa3','aaa4','aa5a'],
  LANG405: ['aaa1','aaa2','aaa3','aaa4','aa5a'],
  LANG406: ['aaa1','aaa2','aaa3','aaa4','aa5a'],
  LANG407: ['aaa1','aaa2','aaa3','aaa4','aa5a'],
  LANG408: ['aaa1','aaa2','aaa3','aaa4','aa5a'],
  LANG409: ['aaa1','aaa2','aaa3','aaa4','aa5a']
};

if (typeof module == 'object') {
  module.exports = lang;
}
