const LANG = {
  inUser_ID: ['아이디를 입력하세요', 'Please enter your ID', '请输入您的身份证'],
  inUser_Pwd: ['비밀번호를 입력하세요', 'Please enter a password', '请输入密码'],
  M_UID: ['아이디를 입력하세요', 'Please enter your ID', '请输入您的身份证'],
  D_UID: ['아이디를 입력하세요', 'Please enter your ID', '请输入您的身份证'],
  D_PASS: ['비밀번호를 입력하세요', 'Please enter a password', '请输入密码'],
  CUR_PW: ['비밀번호를 입력하세요', 'Please enter a password', '请输入密码'],
  D_AB: ['후원라인을 선택해주세요', 'Please enter a Sponsored Position', '请输入密码'],
  D_PWEMAIL: ['비밀번호 확인을 입력하세요', 'Please enter a password confirmation', '请输入密码确认'],
  UN_ED_NAME: ['이름을 입력하세요', 'Please enter your name', '请输入你的名字'],
  D_RID: ['추천 아이디를 검색하세요', 'Search for recommended ID', '搜索推荐的ID'],
  D_SID: ['후원 아이디를 검색하세요', 'Search for patron ID', '搜索推荐的ID'],
  D_EMAIL: ['이메일을 입력하세요', 'Please enter your email', '请输入您的电子邮件'],
  D_MAIL: ['이메일을 입력하세요', 'Please enter your email', '请输入您的电子邮件'],
  D_COUNTRY: ['국가를 선택해주세요', 'Please select a country', '请选择一个国家'],
  SMS_KEY: ['이메일 인증을 진행하세요', 'Proceed with email verification', 'MM'],
  idcheck: ['아이디 중복검사를 진행해주세요', 'Proceed with duplicate ID check', '进行重复的ID检查'],
  D_HP: ['휴대폰 번호를 입력하세요', 'id', '继续进行电子邮件验证'],
  D_SMSNO: ['인증번호를 입력해주세요', 'Please enter a verification number', '请输入验证码'],
  UN_ED_ADDR1: ['주소를 입력해주세요', 'Please enter your address', '请输入您的地址'],
  name: ['이름을 입력해주세요', 'Input your name, please', '请输入你的名字'],
  LANG1: ['약관에 모두 동의 하셔야 이용이 가능하십니다.', 'You must accept all the terms in order to use it.', '您必须接受所有条款才能使用它。'],
  LANG2: ['가입이 완료되었습니다!', 'Sign up is complete!', '注册完成！'],
  LANG3: ['또는', 'or', '或'],
  LANG4: ['메일이 정상 전송되었습니다.', 'Your message has been sent normally', '您的信息已正常发送'],
  LANG5: ['메일 발송에 실패 하였습니다.', 'Failed to send mail.', '无法发送邮件。'],
  D_SMSNO: ['인증번호를 입력해주세요', 'Please enter a verification number', '请输入验证码'],
  LANG7: ['또는', 'or', '或'],
  LANG8: ['ㅡㅡㅡㅡ', 'ㅡㅡㅡ', 'ㅡㅡㅡㅡ'],
  LANG9: ['로그아웃 되었습니다', 'You have been logged out', '您已登出'],
  UN_ED_ADDR2: ['주소를 입력해주세요', 'Please enter your address', '请输入您的地址'],
  MEMO: ['메모를 입력해주세요', 'Please enter a note', '请输入备注'],
  D_QTY: ['수량을 입력해주세요', 'Please enter a quantity', '请输入数量'],
  GS_SUID: ['아이디 검색후 이용해 주세요', 'Please use after ID search', 'ID查询后请使用'],
  GS_UID: ['아이디 검색후 이용해 주세요', 'Please use after ID search', 'ID查询后请使用'],
  LANG10: ['로그인', 'SIGN IN', '登入'],
  LANG11: ['회원가입', 'SIGN UP', '成为会员'],
  LANG12: ['서비스 점검 중입니다. 잠시만 기다려 주십시오', 'Checking server. Please wait a moment', '正在检查服务。 请稍等'],
  LANG13: ['아이디와 비밀번호를 확인하세요', 'Please check your username and password', '请检查您的用户名和密码'],
  LANG14: ['검색', 'Search', '搜寻'],
  LANG15: ['국적 선택', 'SELECT REGION', '国籍选择'],
  LANG16: ['이메일 주소는 비밀번호입니다.', 'E-mail address will be a password.', '您的电子邮件地址是一个密码。'],
  LANG17: ['이메일 확인 코드 보내기', 'Send confirm code for E-mail', '发送电子邮件验证码'],
  LANG18: ['확인', 'Confirm', '好啦'],
  LANG19: ['ID 중복검사', 'ID redundancy', '身份证重复检查'],
  LANG20: ['이 ID는 현재 사용 가능합니다.', 'This ID is currently available.', '该ID当前可用'],
  LANG21: ['이 ID를 사용 하시겠습니까?', 'Do you want to use this ID?', '您要使用这个ID吗？'],
  LANG22: ['다른 아이디를 이용해주세요', 'Please use a different ID.', '请使用其他ID'],
  LANG23: ['닫기', 'Close', '关门'],
  LANG24: ['메일 인증', 'Mail authentication', '邮件认证'],
  LANG25: ['추천인의 사용자 이름을 선택하십시오.', 'Select Referrer\'s Username', '请选择推荐人的用户名。'],
  LANG26: ['저장', 'Save', '保存到'],
  LANG27: ['인증메일을 발송하였습니다', 'Send a authentication code to your mail.', '您的信息已正常发送'],
  LANG28: ['메일 발송에 실패하였습니다', 'Failed to send mail.', '无法发送邮件。'],
  LANG29: ['인증 번호가 유효하지 않습니다.', 'Verification number is invalid.', '授权号无效。'],
  LANG30: ['가입을 축하합니다!', 'Congratulations on joining.', '恭喜您加入'],
  LANG31: ['날짜', 'Date', '日期'],
  LANG32: ['제목', 'Subject', '职称'],
  LANG33: ['추천인', 'Referrer', '推荐人'],
  LANG34: ['내 스폰서', 'My Sponsor', '我的赞助商'],
  LANG35: ['종합 추천', 'Total Referrer', '一般建议'],
  LANG36: ['종합 스폰', 'Total Sponsor', '总产卵'],
  LANG37: ['내 총 판매량', 'Total My Sales', '我的总销量'],
  LANG38: ['총 추천 판매량', 'Total Referrer Sales', '推荐总销量'],
  LANG39: ['총 후원 판매량', 'Total Sponsor Sales', '赞助销售总额'],
  LANG40: ['총 보너스', 'Total Bonus', '总奖金'],
  LANG41: ['비밀번호 변경', 'Change Password', '修改密码'],
  LANG42: ['새로운 이메일로 전송', 'Send confirm code for NEW E-mail', '发送到新电子邮件'],
  LANG43: ['저장', 'Save Change', '保存到'],
  LANG44: ['인증', 'Authentication', '资质认证'],
  LANG45: ['인증 앱 다운로드', 'Download Authentication app', '下载身份验证应用'],
  LANG46: ['코드 복사', 'Copy Auth Code', '复制代码'],
  LANG47: ['비밀번호 변경 성공', 'Password change success', '密码修改成功'],
  LANG48: ['비밀번호 변경 실패', 'Password change failed', '密码更改失败'],
  LANG49: ['내 금액', 'My Balance', '我的金额'],
  LANG50: ['전체 금액', 'Total Balance', '总金额'],
  LANG51: ['내 OUT 보너스', 'My Bonus For OUT', '我的OUT奖金'],
  LANG52: ['스폰서 검색', 'Sponsor Register', '赞助搜索'],
  LANG53: ['등록', 'Registration', '报名'],
  LANG54: ['기록', 'History', '记录'],
  LANG55: ['금액을 확인해주세요', 'Please check the amount', '请检查金额'],
  LANG56: ['값을 확인해 주세요', 'Please check the value', '请检查值'],
  LANG57: ['없는회원입니다', 'I am not a member', '我不是会员'],
  LANG58: ['잔액이 부족합니다.', 'You have run out of balance.', '您的余额已用尽。'],
  LANG59: ['시스템에러.', 'system error.', '系统错误'],
  LANG60: ['성공', 'Processing completed', '成功'],
  LANG61: ['선택한 후원인이 입금 대기중입니다', 'The sponsor you selected is waiting to be deposited', '您选择的赞助商正在等待入场'],
  LANG62: ['내 EOS 지갑 주소', 'My EOS Wallet Address', '我的EOS钱包地址'],
  LANG63: ['계좌 주소', 'Account Address', '帐号地址'],
  LANG64: ['메모 주소', 'MEMO Address', '备忘地址'],
  LANG65: ['복사', 'Copy', '复制'],
  LANG66: ['EOS 출금 주소', 'Withdrawal EOS Address', 'EOS提现地址'],
  LANG67: ['이메일로 OTP 코드 전송', 'Send E-Mail OTP code', '通过电子邮件发送OTP代码'],
  LANG68: ['EOS 출금', 'Withdrawal EOS', 'EOS退出'],
  LANG69: ['출금 기록', 'Widrawal History', '提款记录'],
  LANG70: ['주소', 'Address', '住址'],
  LANG71: ['메모', 'Memo', '备忘'],
  LANG72: ['상태', 'Status', '州'],
  LANG73: ['이체 신청에 성공하였습니다', 'Successful transfer request', '成功的转移请求'],
  LANG74: ['잔고가 부족합니다.', 'You have run out of funds.', '您的资金用完了。'],
  LANG75: ['금액의 오류가있습니다', 'There is an error in the amount', '金额有误'],
  LANG76: ['보내는 사람이없습니다', 'No sender', '没有发件人'],
  LANG77: ['이미 승인받은 상태입니다', 'Already approved', '已经批准'],
  LANG78: ['존재하는 아이디입니다', 'ID exists', 'ID已存在'],
  LANG79: ['5분 후 다시이용해주세요', 'Please try again in 5 minutes', '请在5分钟后重试'],
  LANG80: ['대시보드', 'Dashboard', '仪表板'],
  LANG81: ['프로필 관리', 'Manage Profile', '个人资料管理'],
  LANG82: ['내 EOS 지갑', 'My EOS Wallet', '我的EOS钱包'],
  LANG83: ['내 EOS 보너스', 'My EOS Bonus', '我的EOS奖金'],
  LANG84: ['ETBC 증가', 'ETBC Upstairs', 'ETBC增加'],
  LANG85: ['팀 정보', 'Team Information', '团队信息'],
  LANG86: ['레벨 구조', 'Level Structure', '等级结构'],
  LANG87: ['이진 트리', 'Binary Tree', '二叉树'],
  LANG88: ['ETBC 뉴스', 'ETBC News', 'ETBC新闻'],
  LANG89: ['지원센터', 'Support Center', '支援中心'],
  LANG90: ['로그아웃', 'Sign Out', '登出'],
  LANG91: ['출금은 10단위로만 신청가능합니다(ex 10,20,30...)', 'Withdrawals can only be made in 10 units (ex 10,20,30 ...)', '提款只能以10个单位进行（例如10、20、30 ...）'],
  LANG92: ['비밀번호가 일치하지않습니다', 'Passwords do not match', 'ㅡㅡ'],
  LANG93: ['이용이 불가능한 아이디입니다', 'This ID is not available.', '该ID不可用。'],
  LANG94: ['중복된 이메일', 'Duplicate email', '电子邮件重复'],
  LANG95: ['비밀번호가 일치하지않습니다', 'Passwords do not match', 'ㅡㅡ'],
  LANG96: ['이용할수없는 아이디입니다.', 'ID not available', 'ㅡㅡ'],
  LANG97: ['인증이 완료되었습니다', 'Certification completed', 'ㅡㅡ'],
  LANG98: ['인증번호가 잘못되었습니다', 'Verification number is invalid', 'ㅡㅡ'],
  LANG99: ['매출금을 입력해주세요!', 'Please enter a payout!', 'ㅡㅡ'],
  LANG101: ['매출 신청이 완료되었습니다!', 'Your sales application is complete!', 'ㅡㅡ'],
  LANG102: ['매출에 실패 하였습니다. 잠시후 다시 시도해주세요', 'The sales failed. Please try again in a few minutes', 'ㅡㅡ'],
  LANG103: ['주소를 확인해 주세요', 'Please confirm your address', 'ㅡㅡ'],
  LANG104: ['출금 성공', 'Withdrawal success', 'ㅡㅡ'],
  LANG105: ['출금실패(주소,잔액 확인)', 'Withdrawal failure (address, balance check)', 'ㅡㅡ'],
  LANG106: ['mmm', 'ㅡㅡ', 'ㅡㅡ'],
  LANG107: ['mmm', 'ㅡㅡ', 'ㅡㅡ'],
  LANG108: ['mmm', 'ㅡㅡ', 'ㅡㅡ'],
  LANG109: ['mmm', 'ㅡㅡ', 'ㅡㅡ']
}
var lang = function(val) {
  return LANG[val][1]
}
